# Generated by Django 4.2.23 on 2025-08-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_accesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='main', max_length=50)),
                ('hashed_pin', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
