# Generated by Django 4.2.23 on 2025-08-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_doorpin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, max_length=45)),
                ('attempts', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
