# Generated by Django 4.2.23 on 2025-08-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_doorevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorevent',
            name='topic',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
